## Importing NumPy

In [2]:
import numpy as np

## Creating Arrays

In [3]:
# 1D Array
arr1d = np.array([1, 2, 3, 4, 5])


In [4]:
# 2D Array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
# Zeros, Ones, and Identity Matrices
zeros = np.zeros((3, 3))
ones = np.ones((2, 2))
identity = np.eye(3)

In [6]:
# Random Arrays
rand_arr = np.random.rand(3, 3)  # Uniform [0,1]
rand_ints = np.random.randint(1, 10, (3, 3))  # Random integers

## Array Properties

In [7]:
arr=np.array([1,2,3,4,5])

In [14]:
print('shape_is', arr.shape)   # Get shape (rows, columns)
print('number_of_dimensions_is', arr.ndim)    # Get number of dimensions
print('number_of_elements', arr.size)    # Get total number of elements
print('type_of_elements', arr.dtype)   # Get data type of elements

shape_is (5,)
number_of_dimensions_is 1
number_of_elements 5
type_of_elements int32


## Indexing & Slicing

In [9]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # First element
print(arr[-1]) # Last element
print(arr[1:4])  # Slice from index 1 to 3

10
50
[20 30 40]


## Reshaping Arrays

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))

## Mathematical Operations

In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [14]:
sum_arr = arr1 + arr2  # Element-wise addition
diff_arr = arr1 - arr2 # Element-wise subtraction
prod_arr = arr1 * arr2 # Element-wise multiplication
div_arr = arr1 / arr2  # Element-wise division

In [15]:
np.exp(arr1)  # Exponential
np.sqrt(arr1) # Square root
np.log(arr1)  # Natural logarithm

array([0.        , 0.69314718, 1.09861229])

## Aggregation Functions

In [16]:
arr = np.array([1, 2, 3, 4, 5])
np.sum(arr)   # Sum of elements
np.mean(arr)  # Mean (average)
np.min(arr)   # Minimum value
np.max(arr)   # Maximum value
np.std(arr)   # Standard deviation

1.4142135623730951

## Broadcasting

In [17]:
arr = np.array([1, 2, 3])
print(arr + 10)  # Add scalar to each element

[11 12 13]


## Stacking & Concatenation

In [18]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [19]:
# Vertical Stack
vstacked = np.vstack((arr1, arr2))

In [20]:
# Horizontal Stack
hstacked = np.hstack((arr1, arr2))

## Linear Algebra

In [21]:
mat = np.array([[1, 2], [3, 4]])
det = np.linalg.det(mat)  # Determinant
inv = np.linalg.inv(mat)  # Inverse

## Random Functions

In [22]:
np.random.seed(42)  # Set seed for reproducibility
rand_vals = np.random.rand(3, 3)

## Saving & Loading

In [23]:
np.save("array.npy", arr)  # Save array
loaded_arr = np.load("array.npy")  # Load array

## Useful Tricks

In [24]:
np.unique(arr)  # Get unique elements
np.sort(arr)    # Sort elements
np.argsort(arr) # Get sorted indices

array([0, 1, 2], dtype=int64)